name: Build

on:
  push:
    branches:
    - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.35
  test:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'macos-11', 'windows-2019']
        go: ['1.17.x', '1.16.x']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: |
        make test
        go run ./cmd/osstat
